Imports AForge.Video
Imports AForge.Video.DirectShow
Imports System.IO
Imports ZXing
Imports MySql.Data.MySqlClient
Imports System.Management
Imports System.Threading

Public Class frmScanStudent
    Dim vcd As VideoCaptureDevice
    Dim bmp As Bitmap
    Dim rcvdata As String = ""
    Private Sub Captured(sender As Object, eventArgs As NewFrameEventArgs)
        bmp = DirectCast(eventArgs.Frame.Clone(), Bitmap)

        Dim filter = New AForge.Imaging.Filters.Mirror(False, True)
        Dim mirroredBmp = filter.Apply(bmp)

        PictureBox1.Image = mirroredBmp
    End Sub

    Public Function ModemsConnected() As String
        Dim modems As String = ""
        Try
            Dim searcher As New ManagementObjectSearcher(
                "root\CIMV2",
                "SELECT * FROM Win32_POTSModem")

            For Each queryObj As ManagementObject In searcher.Get()
                If queryObj("Status") = "OK" Then
                    modems = modems & (queryObj("AttachedTo") & " - " & queryObj("Description") & "***")
                End If
            Next
        Catch err As ManagementException
            MsgBox("error")
            Return ""
        End Try
        Return modems
    End Function

    Private Sub frmScanStudent_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Dim vcdf As New VideoCaptureDeviceForm
        day_today.Text = Format(DateTime.Now, "Long Date")

        Dim ports() As String
        ports = Split(ModemsConnected(), "***")
        For i As Integer = 0 To ports.Length - 2
            cmbConnect.Items.Add(ports(i))
        Next

        If vcdf.ShowDialog = DialogResult.OK Then
            vcd = vcdf.VideoDevice
            AddHandler vcd.NewFrame, New NewFrameEventHandler(AddressOf Captured)
            vcd.Start()
            Timer1.Start()
        Else
            Me.Close()
        End If
    End Sub

    Private Sub Timer1_Tick(sender As Object, e As EventArgs) Handles Timer1.Tick
        Dim Reader As New BarcodeReader()
        Dim result As Result = Reader.Decode(CType(PictureBox1.Image, Bitmap))
        Try
            Dim currentDateTime = DateTime.Now
            lblClock.Text = currentDateTime.ToString("hh:mm:ss tt").ToUpper
            Dim logType = GetStudentLogTypeFromDateTime(currentDateTime)

            If logType = StudentLogType.TimeInAM Then
                timeStatus.Text = "TIME IN (AM)"
            ElseIf logType = StudentLogType.TimeOutAM Then
                timeStatus.Text = "TIME OUT (AM)"
            ElseIf logType = StudentLogType.TimeInPM Then
                timeStatus.Text = "TIME IN (PM)"
            ElseIf logType = StudentLogType.TimeOutPM Then
                timeStatus.Text = "TIME OUT (PM)"
            Else
                timeStatus.Text = "[no data]"
            End If

            If result Is Nothing Then
                Return
            End If


            If Not IsNumeric(result.Text) Or result.Text.Count <> 12 Then
                Timer1.Stop()
                MessageBox.Show("Invalid QR Code", "Use the QR Code generated by the system.", MessageBoxButtons.OK, MessageBoxIcon.Question)
                Timer1.Start()
                Return
            End If

            SearchStudent(result.Text, currentDateTime, logType)

        Catch ex As Exception

        End Try

    End Sub

    Private Sub SearchStudent(ScannedLRN As String, currentDateTime As DateTime, logType As StudentLogType)
        Try
            conn.Open()
            comm = New MySqlCommand("SELECT * FROM tbl_student WHERE lrn = '" & ScannedLRN & "'", conn)
            adapter = New MySqlDataAdapter(comm)
            Dim table As New DataTable()
            adapter.Fill(table)

            If table.Rows.Count > 0 Then
                txtLRN.Text = table.Rows(0).Item(1).ToString()
                txtFname.Text = table.Rows(0).Item(2).ToString()
                txtMname.Text = table.Rows(0).Item(3).ToString()
                txtLname.Text = table.Rows(0).Item(4).ToString()
                If table.Rows(0).Item(5).ToString() = "Male" Then
                    cmbGender.SelectedIndex = 0
                Else
                    cmbGender.SelectedIndex = 1
                End If
                txtAddress.Text = table.Rows(0).Item(6).ToString()
                txtParent.Text = table.Rows(0).Item(7).ToString()
                txtContactNo.Text = table.Rows(0).Item(8).ToString()
                txtEmail.Text = table.Rows(0).Item(9).ToString()
                If table.Rows(0).Item(10) IsNot Nothing Then
                    Dim ms As New MemoryStream(CType(table.Rows(0).Item(10), Byte()))
                    ProfileContainer.Image = Image.FromStream(ms)
                End If

                Dim tts = CreateObject("SAPI.spvoice")
                tts.speak("Welcome " & txtFname.Text & " " & txtMname.Text & " " & txtLname.Text)
                conn.Close()

                If logType = StudentLogType.TimeInAM Or logType = StudentLogType.TimeOutPM Then
                    SendSMS(txtContactNo.Text, txtFname.Text & " " & txtLname.Text & " " & timeStatus.Text & " Apokon Elementary School at " & lblClock.Text)
                    InsertToLogs(txtLRN.Text, currentDateTime)
                End If
            End If
        Catch ex As Exception
            conn.Close()
            MessageBox.Show(ex.Message)
        Finally
            conn.Dispose()
        End Try
        conn.Close()
    End Sub

    Private Sub SendSMS(pNumber As String, smsContent As String)
        Try
            With SerialPort1
                .Write("at" & vbCrLf)
                Threading.Thread.Sleep(1000)
                .Write("at+cmgf=1" & vbCrLf)
                Threading.Thread.Sleep(1000)
                .Write("at+cmgs=" & Chr(34) & pNumber & Chr(34) & vbCrLf)
                .Write(smsContent & Chr(26))
                Threading.Thread.Sleep(1000)
                MsgBox(rcvdata.ToString)
            End With
            If rcvdata.ToString.Contains(">") Then
                MsgBox("Message Sent")
            Else
                MsgBox("Error!")
            End If
        Catch ex As Exception

        End Try
    End Sub
    Private Sub frmScanStudent_FormClosed(sender As Object, e As FormClosedEventArgs) Handles MyBase.FormClosed
        If vcd Is Nothing Then
            Return
        End If

        Try
            vcd.Stop()
        Catch ex As Exception

        End Try
        Me.Dispose()
        SerialPort1.Dispose()
        SerialPort1.Close()
        Me.Close()
    End Sub

    Private Sub Guna2Button2_Click(sender As Object, e As EventArgs) Handles Guna2Button2.Click
        Try
            With SerialPort1
                .PortName = lblPort.Text
                .BaudRate = 9600
                .Parity = IO.Ports.Parity.None
                .DataBits = 8
                .StopBits = IO.Ports.StopBits.One
                .Handshake = IO.Ports.Handshake.None
                .RtsEnable = True
                .ReceivedBytesThreshold = 1
                .NewLine = vbCr
                .ReadTimeout = 1000
                .Open()
            End With

            If SerialPort1.IsOpen Then
                lblStatus.Text = "Connected"
                lblStatus.ForeColor = Color.Green
            Else
                lblStatus.Text = "Error"
                lblStatus.ForeColor = Color.DarkRed
                SerialPort1.Close()
            End If
        Catch ex As Exception
            MsgBox(ex.Message)
        End Try
    End Sub

    Private Sub cmbConnect_SelectedValueChanged(sender As Object, e As EventArgs) Handles cmbConnect.SelectedValueChanged
        lblPort.Text = Trim(Mid(cmbConnect.Text, 1, 5))
    End Sub

    Private Sub SerialPort1_DataReceived(sender As Object, e As Ports.SerialDataReceivedEventArgs) Handles SerialPort1.DataReceived
        Dim datain As String = ""
        Dim numbytes As Integer = SerialPort1.BytesToRead
        For i As Integer = 1 To numbytes
            datain &= Chr(SerialPort1.ReadChar)
        Next
        test(datain)
    End Sub

    Private Sub test(ByVal indata As String)
        rcvdata &= indata
    End Sub

End Class